# Generated by Django 3.2.7 on 2021-10-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_person_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_free',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='is_weak',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
